# Generated by Django 6.0.5 on 2026-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('dob', models.DateField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
