# Generated by Django 6.0.5 on 2026-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='profile_pic',
            field=models.ImageField(default='actors/default_image.jpg', upload_to='actors'),
        ),
    ]
